language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - docker

branches:
  only:
    - master
    - dev-branch
before_install:
  - docker build . -t africinnovate-laundry:latest
  - docker run

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$REGISTRY_PASS"