language: node_js
node_js: 
  - node
cache:
  directories:
    - node_modules
services:
  - docker

branches:
  only:
    - master
    - dev-branch
before_install:
  - docker build . -t cejowisz/africinnovate-laundry
  - docker run -it --rm -p 80:3000 africinnovate-laundry /bin/bash

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
    provider: script
    script: docker push africinnovate-laundry
    on:
      branch: dev-branch